spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/transaction-service
    username: root
    password: Huynguyen11102002
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      name: balance_updates

server:
  port: 9000



