server:
  port: 9090
spring:
  application:
    name: "accounts"
  datasource:
    url: jdbc:mysql://localhost:3306/account-service
    username: root
    password: Huynguyen11102002
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      acks: -1
      retries: 1
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        request:
          timeout:
            ms: 1
        enable:
          idempotence: true
        max:
          in:
            flight:
              requests:
                per:
                  connection:5
    consumer:
      auto-offset-reset: earliest
      group-id: myGroup
  sql:
    init:
      mode: always
